"""empty message

Revision ID: 0d3d893d2828
Revises: 2596ece2987f
Create Date: 2021-04-17 04:23:35.749126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3d893d2828'
down_revision = '2596ece2987f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorities', 'user', ['userId'], ['userId'])
    op.create_foreign_key(None, 'favorities', 'planets', ['planetId'], ['idPlanet'])
    op.create_foreign_key(None, 'favorities', 'characters', ['characterId'], ['idCharacter'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorities', type_='foreignkey')
    op.drop_constraint(None, 'favorities', type_='foreignkey')
    op.drop_constraint(None, 'favorities', type_='foreignkey')
    # ### end Alembic commands ###
