"""empty message

Revision ID: 2596ece2987f
Revises: d97fd32c9b5b
Create Date: 2021-04-17 04:23:09.507610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2596ece2987f'
down_revision = 'd97fd32c9b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favorities_ibfk_1', 'favorities', type_='foreignkey')
    op.drop_constraint('favorities_ibfk_3', 'favorities', type_='foreignkey')
    op.drop_constraint('favorities_ibfk_2', 'favorities', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('favorities_ibfk_2', 'favorities', 'planets', ['planetId'], ['idPlanet'])
    op.create_foreign_key('favorities_ibfk_3', 'favorities', 'user', ['userId'], ['userId'])
    op.create_foreign_key('favorities_ibfk_1', 'favorities', 'characters', ['characterId'], ['idCharacter'])
    # ### end Alembic commands ###
